# Array(数组)
* rank

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [10]:
a=a.reshape((1,-1))

In [11]:
a.shape

(1, 3)

# Indexing

In [12]:
a=np.array([1,2,3,4],[5,6,7,8,],[9,10,11,12])

ValueError: only 2 non-keyword arguments accepted

In [13]:
a=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12])

SyntaxError: invalid syntax (<ipython-input-13-48c16fda2562>, line 1)

In [14]:
a=np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])

In [15]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
a[-2:,1:3]

array([[ 6,  7],
       [10, 11]])

In [17]:
a.[np.array(3),1]+=10

SyntaxError: invalid syntax (<ipython-input-17-779ff030587a>, line 1)

In [18]:
a[np.array(3),1]+=10

IndexError: index 3 is out of bounds for axis 0 with size 3

In [19]:
a[np.arange(3),1]+=10

In [20]:
a


array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [21]:
a[np.arrange(3),[1,1,1]]+=10

AttributeError: module 'numpy' has no attribute 'arrange'

In [22]:
a[np.arange(3),[1,1,1]]+=10

In [23]:
a


array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

In [24]:
a[[0,1,2].[1,1,1]]+=10

SyntaxError: invalid syntax (<ipython-input-24-b53004f6c0bc>, line 1)

In [25]:
a[[0,1,2],[1,1,1]]+=10

In [26]:
a


array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

In [27]:
index=a>10

In [28]:
index


array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [29]:
a[index]

array([32, 36, 40, 11, 12])

In [30]:
a[a>10]

array([32, 36, 40, 11, 12])

In [31]:
a=np.array([1.2,2.2])

In [32]:
a.dtype

dtype('float64')

In [34]:
a=np.array([1.2,2.2],dtype=np.int64)

In [35]:
a

array([1, 2], dtype=int64)

In [36]:
eye(2)

NameError: name 'eye' is not defined

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 数学运算与常用函数

In [42]:
a=np.array([[1,2],[3,4]])

In [43]:
b=np.array([[5,6],[6,5]])

In [44]:
a+b

array([[6, 8],
       [9, 9]])

In [45]:
a-b

array([[-4, -4],
       [-3, -1]])

In [46]:
a*b

array([[ 5, 12],
       [18, 20]])

In [47]:
a@b

array([[17, 16],
       [39, 38]])